/*
 * CIRA SHG Windex API
 * CIRALabs SecureHomeGateway Windex API: between smartphone and router
 *
 * The version of the OpenAPI document: 1.0.0-current
 * Contact: securehomegateway@cira.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ca.cira.shg.windex.model;

import java.util.Objects;
import java.util.Arrays;
import ca.cira.shg.windex.model.DeviceBodyTrafficCounts;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.threeten.bp.OffsetDateTime;

/**
 * DeviceBody
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-06-25T12:38:14.452071-04:00[America/Toronto]")
public class DeviceBody {
  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_FQDN = "fqdn";
  @SerializedName(SERIALIZED_NAME_FQDN)
  private String fqdn;

  public static final String SERIALIZED_NAME_EUI64 = "eui64";
  @SerializedName(SERIALIZED_NAME_EUI64)
  private String eui64;

  public static final String SERIALIZED_NAME_CREATED_AT = "created_at";
  @SerializedName(SERIALIZED_NAME_CREATED_AT)
  private OffsetDateTime createdAt;

  public static final String SERIALIZED_NAME_UPDATED_AT = "updated_at";
  @SerializedName(SERIALIZED_NAME_UPDATED_AT)
  private OffsetDateTime updatedAt;

  public static final String SERIALIZED_NAME_DEVICE_TYPE_ID = "device_type_id";
  @SerializedName(SERIALIZED_NAME_DEVICE_TYPE_ID)
  private Integer deviceTypeId;

  public static final String SERIALIZED_NAME_MANUFACTURER_ID = "manufacturer_id";
  @SerializedName(SERIALIZED_NAME_MANUFACTURER_ID)
  private Integer manufacturerId;

  public static final String SERIALIZED_NAME_IDEV_ID = "idev_id";
  @SerializedName(SERIALIZED_NAME_IDEV_ID)
  private String idevId;

  public static final String SERIALIZED_NAME_TRAFFIC_COUNTS = "traffic_counts";
  @SerializedName(SERIALIZED_NAME_TRAFFIC_COUNTS)
  private DeviceBodyTrafficCounts trafficCounts = null;

  public static final String SERIALIZED_NAME_MUD_URL = "mud_url";
  @SerializedName(SERIALIZED_NAME_MUD_URL)
  private String mudUrl;

  public static final String SERIALIZED_NAME_PROFILE_ID = "profile_id";
  @SerializedName(SERIALIZED_NAME_PROFILE_ID)
  private Integer profileId;

  public static final String SERIALIZED_NAME_CURRENT_VLAN = "current_vlan";
  @SerializedName(SERIALIZED_NAME_CURRENT_VLAN)
  private String currentVlan;

  public static final String SERIALIZED_NAME_WAN_ENABLED = "wan_enabled";
  @SerializedName(SERIALIZED_NAME_WAN_ENABLED)
  private Boolean wanEnabled;

  public static final String SERIALIZED_NAME_LAN_ENABLED = "lan_enabled";
  @SerializedName(SERIALIZED_NAME_LAN_ENABLED)
  private Boolean lanEnabled;

  public static final String SERIALIZED_NAME_FIREWALL_RULES = "firewall_rules";
  @SerializedName(SERIALIZED_NAME_FIREWALL_RULES)
  private List<Object> firewallRules = new ArrayList<Object>();

  public static final String SERIALIZED_NAME_FIREWALL_RULE_NAMES = "firewall_rule_names";
  @SerializedName(SERIALIZED_NAME_FIREWALL_RULE_NAMES)
  private List<Object> firewallRuleNames = new ArrayList<Object>();

  public static final String SERIALIZED_NAME_DELETED = "deleted";
  @SerializedName(SERIALIZED_NAME_DELETED)
  private Boolean deleted = false;

  public static final String SERIALIZED_NAME_QUARANTEED = "quaranteed";
  @SerializedName(SERIALIZED_NAME_QUARANTEED)
  private Boolean quaranteed;

  public static final String SERIALIZED_NAME_DEVICE_ENABLED = "device_enabled";
  @SerializedName(SERIALIZED_NAME_DEVICE_ENABLED)
  private Boolean deviceEnabled;

  public static final String SERIALIZED_NAME_DEVICE_STATE = "device_state";
  @SerializedName(SERIALIZED_NAME_DEVICE_STATE)
  private String deviceState;

  public static final String SERIALIZED_NAME_FAILURE_DETAILS = "failure_details";
  @SerializedName(SERIALIZED_NAME_FAILURE_DETAILS)
  private Object failureDetails = null;

  public static final String SERIALIZED_NAME_IPV4 = "ipv4";
  @SerializedName(SERIALIZED_NAME_IPV4)
  private String ipv4;

  public static final String SERIALIZED_NAME_IPV6 = "ipv6";
  @SerializedName(SERIALIZED_NAME_IPV6)
  private String ipv6;

  public static final String SERIALIZED_NAME_ACP_PREFIX = "acp_prefix";
  @SerializedName(SERIALIZED_NAME_ACP_PREFIX)
  private String acpPrefix;

  public static final String SERIALIZED_NAME_IDEVID_HASH = "idevid_hash";
  @SerializedName(SERIALIZED_NAME_IDEVID_HASH)
  private String idevidHash;

  public static final String SERIALIZED_NAME_LDEVID = "ldevid";
  @SerializedName(SERIALIZED_NAME_LDEVID)
  private String ldevid;

  public static final String SERIALIZED_NAME_LDEVID_HASH = "ldevid_hash";
  @SerializedName(SERIALIZED_NAME_LDEVID_HASH)
  private String ldevidHash;

  public static final String SERIALIZED_NAME_WPA_KEY = "wpa_key";
  @SerializedName(SERIALIZED_NAME_WPA_KEY)
  private String wpaKey;

  public DeviceBody name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Name of the device if available
   * @return name
  **/
  @ApiModelProperty(value = "Name of the device if available")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public DeviceBody fqdn(String fqdn) {
    this.fqdn = fqdn;
    return this;
  }

   /**
   * Get fqdn
   * @return fqdn
  **/
  @ApiModelProperty(value = "")
  public String getFqdn() {
    return fqdn;
  }

  public void setFqdn(String fqdn) {
    this.fqdn = fqdn;
  }

  public DeviceBody eui64(String eui64) {
    this.eui64 = eui64;
    return this;
  }

   /**
   * Get eui64
   * @return eui64
  **/
  @ApiModelProperty(value = "")
  public String getEui64() {
    return eui64;
  }

  public void setEui64(String eui64) {
    this.eui64 = eui64;
  }

  public DeviceBody createdAt(OffsetDateTime createdAt) {
    this.createdAt = createdAt;
    return this;
  }

   /**
   * Device creation datetime
   * @return createdAt
  **/
  @ApiModelProperty(value = "Device creation datetime")
  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }

  public DeviceBody updatedAt(OffsetDateTime updatedAt) {
    this.updatedAt = updatedAt;
    return this;
  }

   /**
   * Device last update datetime
   * @return updatedAt
  **/
  @ApiModelProperty(value = "Device last update datetime")
  public OffsetDateTime getUpdatedAt() {
    return updatedAt;
  }

  public void setUpdatedAt(OffsetDateTime updatedAt) {
    this.updatedAt = updatedAt;
  }

  public DeviceBody deviceTypeId(Integer deviceTypeId) {
    this.deviceTypeId = deviceTypeId;
    return this;
  }

   /**
   * Get deviceTypeId
   * @return deviceTypeId
  **/
  @ApiModelProperty(value = "")
  public Integer getDeviceTypeId() {
    return deviceTypeId;
  }

  public void setDeviceTypeId(Integer deviceTypeId) {
    this.deviceTypeId = deviceTypeId;
  }

  public DeviceBody manufacturerId(Integer manufacturerId) {
    this.manufacturerId = manufacturerId;
    return this;
  }

   /**
   * Get manufacturerId
   * @return manufacturerId
  **/
  @ApiModelProperty(value = "")
  public Integer getManufacturerId() {
    return manufacturerId;
  }

  public void setManufacturerId(Integer manufacturerId) {
    this.manufacturerId = manufacturerId;
  }

  public DeviceBody idevId(String idevId) {
    this.idevId = idevId;
    return this;
  }

   /**
   * Get idevId
   * @return idevId
  **/
  @ApiModelProperty(value = "")
  public String getIdevId() {
    return idevId;
  }

  public void setIdevId(String idevId) {
    this.idevId = idevId;
  }

  public DeviceBody trafficCounts(DeviceBodyTrafficCounts trafficCounts) {
    this.trafficCounts = trafficCounts;
    return this;
  }

   /**
   * Get trafficCounts
   * @return trafficCounts
  **/
  @ApiModelProperty(value = "")
  public DeviceBodyTrafficCounts getTrafficCounts() {
    return trafficCounts;
  }

  public void setTrafficCounts(DeviceBodyTrafficCounts trafficCounts) {
    this.trafficCounts = trafficCounts;
  }

  public DeviceBody mudUrl(String mudUrl) {
    this.mudUrl = mudUrl;
    return this;
  }

   /**
   * Get mudUrl
   * @return mudUrl
  **/
  @ApiModelProperty(value = "")
  public String getMudUrl() {
    return mudUrl;
  }

  public void setMudUrl(String mudUrl) {
    this.mudUrl = mudUrl;
  }

  public DeviceBody profileId(Integer profileId) {
    this.profileId = profileId;
    return this;
  }

   /**
   * Get profileId
   * @return profileId
  **/
  @ApiModelProperty(value = "")
  public Integer getProfileId() {
    return profileId;
  }

  public void setProfileId(Integer profileId) {
    this.profileId = profileId;
  }

  public DeviceBody currentVlan(String currentVlan) {
    this.currentVlan = currentVlan;
    return this;
  }

   /**
   * Get currentVlan
   * @return currentVlan
  **/
  @ApiModelProperty(value = "")
  public String getCurrentVlan() {
    return currentVlan;
  }

  public void setCurrentVlan(String currentVlan) {
    this.currentVlan = currentVlan;
  }

  public DeviceBody wanEnabled(Boolean wanEnabled) {
    this.wanEnabled = wanEnabled;
    return this;
  }

   /**
   * Get wanEnabled
   * @return wanEnabled
  **/
  @ApiModelProperty(value = "")
  public Boolean getWanEnabled() {
    return wanEnabled;
  }

  public void setWanEnabled(Boolean wanEnabled) {
    this.wanEnabled = wanEnabled;
  }

  public DeviceBody lanEnabled(Boolean lanEnabled) {
    this.lanEnabled = lanEnabled;
    return this;
  }

   /**
   * Get lanEnabled
   * @return lanEnabled
  **/
  @ApiModelProperty(value = "")
  public Boolean getLanEnabled() {
    return lanEnabled;
  }

  public void setLanEnabled(Boolean lanEnabled) {
    this.lanEnabled = lanEnabled;
  }

  public DeviceBody firewallRules(List<Object> firewallRules) {
    this.firewallRules = firewallRules;
    return this;
  }

  public DeviceBody addFirewallRulesItem(Object firewallRulesItem) {
    if (this.firewallRules == null) {
      this.firewallRules = new ArrayList<Object>();
    }
    this.firewallRules.add(firewallRulesItem);
    return this;
  }

   /**
   * Get firewallRules
   * @return firewallRules
  **/
  @ApiModelProperty(value = "")
  public List<Object> getFirewallRules() {
    return firewallRules;
  }

  public void setFirewallRules(List<Object> firewallRules) {
    this.firewallRules = firewallRules;
  }

  public DeviceBody firewallRuleNames(List<Object> firewallRuleNames) {
    this.firewallRuleNames = firewallRuleNames;
    return this;
  }

  public DeviceBody addFirewallRuleNamesItem(Object firewallRuleNamesItem) {
    if (this.firewallRuleNames == null) {
      this.firewallRuleNames = new ArrayList<Object>();
    }
    this.firewallRuleNames.add(firewallRuleNamesItem);
    return this;
  }

   /**
   * Get firewallRuleNames
   * @return firewallRuleNames
  **/
  @ApiModelProperty(value = "")
  public List<Object> getFirewallRuleNames() {
    return firewallRuleNames;
  }

  public void setFirewallRuleNames(List<Object> firewallRuleNames) {
    this.firewallRuleNames = firewallRuleNames;
  }

  public DeviceBody deleted(Boolean deleted) {
    this.deleted = deleted;
    return this;
  }

   /**
   * Get deleted
   * @return deleted
  **/
  @ApiModelProperty(value = "")
  public Boolean getDeleted() {
    return deleted;
  }

  public void setDeleted(Boolean deleted) {
    this.deleted = deleted;
  }

  public DeviceBody quaranteed(Boolean quaranteed) {
    this.quaranteed = quaranteed;
    return this;
  }

   /**
   * Get quaranteed
   * @return quaranteed
  **/
  @ApiModelProperty(value = "")
  public Boolean getQuaranteed() {
    return quaranteed;
  }

  public void setQuaranteed(Boolean quaranteed) {
    this.quaranteed = quaranteed;
  }

  public DeviceBody deviceEnabled(Boolean deviceEnabled) {
    this.deviceEnabled = deviceEnabled;
    return this;
  }

   /**
   * Get deviceEnabled
   * @return deviceEnabled
  **/
  @ApiModelProperty(value = "")
  public Boolean getDeviceEnabled() {
    return deviceEnabled;
  }

  public void setDeviceEnabled(Boolean deviceEnabled) {
    this.deviceEnabled = deviceEnabled;
  }

  public DeviceBody deviceState(String deviceState) {
    this.deviceState = deviceState;
    return this;
  }

   /**
   * Get deviceState
   * @return deviceState
  **/
  @ApiModelProperty(value = "")
  public String getDeviceState() {
    return deviceState;
  }

  public void setDeviceState(String deviceState) {
    this.deviceState = deviceState;
  }

  public DeviceBody failureDetails(Object failureDetails) {
    this.failureDetails = failureDetails;
    return this;
  }

   /**
   * Get failureDetails
   * @return failureDetails
  **/
  @ApiModelProperty(value = "")
  public Object getFailureDetails() {
    return failureDetails;
  }

  public void setFailureDetails(Object failureDetails) {
    this.failureDetails = failureDetails;
  }

  public DeviceBody ipv4(String ipv4) {
    this.ipv4 = ipv4;
    return this;
  }

   /**
   * Get ipv4
   * @return ipv4
  **/
  @ApiModelProperty(value = "")
  public String getIpv4() {
    return ipv4;
  }

  public void setIpv4(String ipv4) {
    this.ipv4 = ipv4;
  }

  public DeviceBody ipv6(String ipv6) {
    this.ipv6 = ipv6;
    return this;
  }

   /**
   * Get ipv6
   * @return ipv6
  **/
  @ApiModelProperty(value = "")
  public String getIpv6() {
    return ipv6;
  }

  public void setIpv6(String ipv6) {
    this.ipv6 = ipv6;
  }

  public DeviceBody acpPrefix(String acpPrefix) {
    this.acpPrefix = acpPrefix;
    return this;
  }

   /**
   * Get acpPrefix
   * @return acpPrefix
  **/
  @ApiModelProperty(value = "")
  public String getAcpPrefix() {
    return acpPrefix;
  }

  public void setAcpPrefix(String acpPrefix) {
    this.acpPrefix = acpPrefix;
  }

  public DeviceBody idevidHash(String idevidHash) {
    this.idevidHash = idevidHash;
    return this;
  }

   /**
   * Get idevidHash
   * @return idevidHash
  **/
  @ApiModelProperty(value = "")
  public String getIdevidHash() {
    return idevidHash;
  }

  public void setIdevidHash(String idevidHash) {
    this.idevidHash = idevidHash;
  }

  public DeviceBody ldevid(String ldevid) {
    this.ldevid = ldevid;
    return this;
  }

   /**
   * Get ldevid
   * @return ldevid
  **/
  @ApiModelProperty(value = "")
  public String getLdevid() {
    return ldevid;
  }

  public void setLdevid(String ldevid) {
    this.ldevid = ldevid;
  }

  public DeviceBody ldevidHash(String ldevidHash) {
    this.ldevidHash = ldevidHash;
    return this;
  }

   /**
   * Get ldevidHash
   * @return ldevidHash
  **/
  @ApiModelProperty(value = "")
  public String getLdevidHash() {
    return ldevidHash;
  }

  public void setLdevidHash(String ldevidHash) {
    this.ldevidHash = ldevidHash;
  }

  public DeviceBody wpaKey(String wpaKey) {
    this.wpaKey = wpaKey;
    return this;
  }

   /**
   * Get wpaKey
   * @return wpaKey
  **/
  @ApiModelProperty(value = "")
  public String getWpaKey() {
    return wpaKey;
  }

  public void setWpaKey(String wpaKey) {
    this.wpaKey = wpaKey;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DeviceBody deviceBody = (DeviceBody) o;
    return Objects.equals(this.name, deviceBody.name) &&
        Objects.equals(this.fqdn, deviceBody.fqdn) &&
        Objects.equals(this.eui64, deviceBody.eui64) &&
        Objects.equals(this.createdAt, deviceBody.createdAt) &&
        Objects.equals(this.updatedAt, deviceBody.updatedAt) &&
        Objects.equals(this.deviceTypeId, deviceBody.deviceTypeId) &&
        Objects.equals(this.manufacturerId, deviceBody.manufacturerId) &&
        Objects.equals(this.idevId, deviceBody.idevId) &&
        Objects.equals(this.trafficCounts, deviceBody.trafficCounts) &&
        Objects.equals(this.mudUrl, deviceBody.mudUrl) &&
        Objects.equals(this.profileId, deviceBody.profileId) &&
        Objects.equals(this.currentVlan, deviceBody.currentVlan) &&
        Objects.equals(this.wanEnabled, deviceBody.wanEnabled) &&
        Objects.equals(this.lanEnabled, deviceBody.lanEnabled) &&
        Objects.equals(this.firewallRules, deviceBody.firewallRules) &&
        Objects.equals(this.firewallRuleNames, deviceBody.firewallRuleNames) &&
        Objects.equals(this.deleted, deviceBody.deleted) &&
        Objects.equals(this.quaranteed, deviceBody.quaranteed) &&
        Objects.equals(this.deviceEnabled, deviceBody.deviceEnabled) &&
        Objects.equals(this.deviceState, deviceBody.deviceState) &&
        Objects.equals(this.failureDetails, deviceBody.failureDetails) &&
        Objects.equals(this.ipv4, deviceBody.ipv4) &&
        Objects.equals(this.ipv6, deviceBody.ipv6) &&
        Objects.equals(this.acpPrefix, deviceBody.acpPrefix) &&
        Objects.equals(this.idevidHash, deviceBody.idevidHash) &&
        Objects.equals(this.ldevid, deviceBody.ldevid) &&
        Objects.equals(this.ldevidHash, deviceBody.ldevidHash) &&
        Objects.equals(this.wpaKey, deviceBody.wpaKey);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, fqdn, eui64, createdAt, updatedAt, deviceTypeId, manufacturerId, idevId, trafficCounts, mudUrl, profileId, currentVlan, wanEnabled, lanEnabled, firewallRules, firewallRuleNames, deleted, quaranteed, deviceEnabled, deviceState, failureDetails, ipv4, ipv6, acpPrefix, idevidHash, ldevid, ldevidHash, wpaKey);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DeviceBody {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    fqdn: ").append(toIndentedString(fqdn)).append("\n");
    sb.append("    eui64: ").append(toIndentedString(eui64)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("    deviceTypeId: ").append(toIndentedString(deviceTypeId)).append("\n");
    sb.append("    manufacturerId: ").append(toIndentedString(manufacturerId)).append("\n");
    sb.append("    idevId: ").append(toIndentedString(idevId)).append("\n");
    sb.append("    trafficCounts: ").append(toIndentedString(trafficCounts)).append("\n");
    sb.append("    mudUrl: ").append(toIndentedString(mudUrl)).append("\n");
    sb.append("    profileId: ").append(toIndentedString(profileId)).append("\n");
    sb.append("    currentVlan: ").append(toIndentedString(currentVlan)).append("\n");
    sb.append("    wanEnabled: ").append(toIndentedString(wanEnabled)).append("\n");
    sb.append("    lanEnabled: ").append(toIndentedString(lanEnabled)).append("\n");
    sb.append("    firewallRules: ").append(toIndentedString(firewallRules)).append("\n");
    sb.append("    firewallRuleNames: ").append(toIndentedString(firewallRuleNames)).append("\n");
    sb.append("    deleted: ").append(toIndentedString(deleted)).append("\n");
    sb.append("    quaranteed: ").append(toIndentedString(quaranteed)).append("\n");
    sb.append("    deviceEnabled: ").append(toIndentedString(deviceEnabled)).append("\n");
    sb.append("    deviceState: ").append(toIndentedString(deviceState)).append("\n");
    sb.append("    failureDetails: ").append(toIndentedString(failureDetails)).append("\n");
    sb.append("    ipv4: ").append(toIndentedString(ipv4)).append("\n");
    sb.append("    ipv6: ").append(toIndentedString(ipv6)).append("\n");
    sb.append("    acpPrefix: ").append(toIndentedString(acpPrefix)).append("\n");
    sb.append("    idevidHash: ").append(toIndentedString(idevidHash)).append("\n");
    sb.append("    ldevid: ").append(toIndentedString(ldevid)).append("\n");
    sb.append("    ldevidHash: ").append(toIndentedString(ldevidHash)).append("\n");
    sb.append("    wpaKey: ").append(toIndentedString(wpaKey)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

