/*
 * CIRA SHG Windex API
 * CIRALabs SecureHomeGateway Windex API: between smartphone and router
 *
 * The version of the OpenAPI document: 1.0.0-current
 * Contact: securehomegateway@cira.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ca.cira.shg.windex.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * DeviceBodyTrafficCounts
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-06-25T12:38:14.452071-04:00[America/Toronto]")
public class DeviceBodyTrafficCounts {
  public static final String SERIALIZED_NAME_BYTES = "bytes";
  @SerializedName(SERIALIZED_NAME_BYTES)
  private List<Integer> bytes = new ArrayList<Integer>();

  public static final String SERIALIZED_NAME_PACKETS = "packets";
  @SerializedName(SERIALIZED_NAME_PACKETS)
  private List<Integer> packets = new ArrayList<Integer>();

  public DeviceBodyTrafficCounts bytes(List<Integer> bytes) {
    this.bytes = bytes;
    return this;
  }

  public DeviceBodyTrafficCounts addBytesItem(Integer bytesItem) {
    if (this.bytes == null) {
      this.bytes = new ArrayList<Integer>();
    }
    this.bytes.add(bytesItem);
    return this;
  }

   /**
   * Get bytes
   * @return bytes
  **/
  @ApiModelProperty(value = "")
  public List<Integer> getBytes() {
    return bytes;
  }

  public void setBytes(List<Integer> bytes) {
    this.bytes = bytes;
  }

  public DeviceBodyTrafficCounts packets(List<Integer> packets) {
    this.packets = packets;
    return this;
  }

  public DeviceBodyTrafficCounts addPacketsItem(Integer packetsItem) {
    if (this.packets == null) {
      this.packets = new ArrayList<Integer>();
    }
    this.packets.add(packetsItem);
    return this;
  }

   /**
   * Get packets
   * @return packets
  **/
  @ApiModelProperty(value = "")
  public List<Integer> getPackets() {
    return packets;
  }

  public void setPackets(List<Integer> packets) {
    this.packets = packets;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DeviceBodyTrafficCounts deviceBodyTrafficCounts = (DeviceBodyTrafficCounts) o;
    return Objects.equals(this.bytes, deviceBodyTrafficCounts.bytes) &&
        Objects.equals(this.packets, deviceBodyTrafficCounts.packets);
  }

  @Override
  public int hashCode() {
    return Objects.hash(bytes, packets);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DeviceBodyTrafficCounts {\n");
    sb.append("    bytes: ").append(toIndentedString(bytes)).append("\n");
    sb.append("    packets: ").append(toIndentedString(packets)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

