/*
 * CIRA SHG Windex API
 * CIRALabs SecureHomeGateway Windex API: between smartphone and router
 *
 * The version of the OpenAPI document: 1.0.0-current
 * Contact: securehomegateway@cira.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ca.cira.shg.windex.model;

import java.util.Objects;
import java.util.Arrays;
import ca.cira.shg.windex.model.DeviceJsonAllOf;
import ca.cira.shg.windex.model.UserBody;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.threeten.bp.OffsetDateTime;

/**
 * UserJson
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-06-25T12:38:14.452071-04:00[America/Toronto]")
public class UserJson {
  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_ADMIN = "admin";
  @SerializedName(SERIALIZED_NAME_ADMIN)
  private Boolean admin = false;

  public static final String SERIALIZED_NAME_ENABLED = "enabled";
  @SerializedName(SERIALIZED_NAME_ENABLED)
  private Boolean enabled = false;

  public static final String SERIALIZED_NAME_PROSPECTIVE = "prospective";
  @SerializedName(SERIALIZED_NAME_PROSPECTIVE)
  private Boolean prospective = true;

  public static final String SERIALIZED_NAME_PUBLIC_KEY = "public_key";
  @SerializedName(SERIALIZED_NAME_PUBLIC_KEY)
  private String publicKey;

  public static final String SERIALIZED_NAME_PREVIOUS_PUBLIC_KEY = "previous_public_key";
  @SerializedName(SERIALIZED_NAME_PREVIOUS_PUBLIC_KEY)
  private String previousPublicKey;

  public static final String SERIALIZED_NAME_LAST_LOGIN = "last_login";
  @SerializedName(SERIALIZED_NAME_LAST_LOGIN)
  private OffsetDateTime lastLogin;

  public static final String SERIALIZED_NAME_FIRST_LOGIN = "first_login";
  @SerializedName(SERIALIZED_NAME_FIRST_LOGIN)
  private OffsetDateTime firstLogin;

  public static final String SERIALIZED_NAME_LAST_LOGIN_IP = "last_login_ip";
  @SerializedName(SERIALIZED_NAME_LAST_LOGIN_IP)
  private String lastLoginIp;

  public static final String SERIALIZED_NAME_CREATED_AT = "created_at";
  @SerializedName(SERIALIZED_NAME_CREATED_AT)
  private OffsetDateTime createdAt;

  public static final String SERIALIZED_NAME_UPDATED_AT = "updated_at";
  @SerializedName(SERIALIZED_NAME_UPDATED_AT)
  private OffsetDateTime updatedAt;

  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private Integer id;

  public UserJson name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Username
   * @return name
  **/
  @ApiModelProperty(value = "Username")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public UserJson admin(Boolean admin) {
    this.admin = admin;
    return this;
  }

   /**
   * Whether user has admin rights
   * @return admin
  **/
  @ApiModelProperty(value = "Whether user has admin rights")
  public Boolean getAdmin() {
    return admin;
  }

  public void setAdmin(Boolean admin) {
    this.admin = admin;
  }

  public UserJson enabled(Boolean enabled) {
    this.enabled = enabled;
    return this;
  }

   /**
   * Whether user is enabled
   * @return enabled
  **/
  @ApiModelProperty(value = "Whether user is enabled")
  public Boolean getEnabled() {
    return enabled;
  }

  public void setEnabled(Boolean enabled) {
    this.enabled = enabled;
  }

  public UserJson prospective(Boolean prospective) {
    this.prospective = prospective;
    return this;
  }

   /**
   * Get prospective
   * @return prospective
  **/
  @ApiModelProperty(value = "")
  public Boolean getProspective() {
    return prospective;
  }

  public void setProspective(Boolean prospective) {
    this.prospective = prospective;
  }

  public UserJson publicKey(String publicKey) {
    this.publicKey = publicKey;
    return this;
  }

   /**
   * Get publicKey
   * @return publicKey
  **/
  @ApiModelProperty(value = "")
  public String getPublicKey() {
    return publicKey;
  }

  public void setPublicKey(String publicKey) {
    this.publicKey = publicKey;
  }

  public UserJson previousPublicKey(String previousPublicKey) {
    this.previousPublicKey = previousPublicKey;
    return this;
  }

   /**
   * Get previousPublicKey
   * @return previousPublicKey
  **/
  @ApiModelProperty(value = "")
  public String getPreviousPublicKey() {
    return previousPublicKey;
  }

  public void setPreviousPublicKey(String previousPublicKey) {
    this.previousPublicKey = previousPublicKey;
  }

  public UserJson lastLogin(OffsetDateTime lastLogin) {
    this.lastLogin = lastLogin;
    return this;
  }

   /**
   * Last login datetime
   * @return lastLogin
  **/
  @ApiModelProperty(value = "Last login datetime")
  public OffsetDateTime getLastLogin() {
    return lastLogin;
  }

  public void setLastLogin(OffsetDateTime lastLogin) {
    this.lastLogin = lastLogin;
  }

  public UserJson firstLogin(OffsetDateTime firstLogin) {
    this.firstLogin = firstLogin;
    return this;
  }

   /**
   * First login datetime
   * @return firstLogin
  **/
  @ApiModelProperty(value = "First login datetime")
  public OffsetDateTime getFirstLogin() {
    return firstLogin;
  }

  public void setFirstLogin(OffsetDateTime firstLogin) {
    this.firstLogin = firstLogin;
  }

  public UserJson lastLoginIp(String lastLoginIp) {
    this.lastLoginIp = lastLoginIp;
    return this;
  }

   /**
   * Get lastLoginIp
   * @return lastLoginIp
  **/
  @ApiModelProperty(value = "")
  public String getLastLoginIp() {
    return lastLoginIp;
  }

  public void setLastLoginIp(String lastLoginIp) {
    this.lastLoginIp = lastLoginIp;
  }

  public UserJson createdAt(OffsetDateTime createdAt) {
    this.createdAt = createdAt;
    return this;
  }

   /**
   * User creation datetime
   * @return createdAt
  **/
  @ApiModelProperty(value = "User creation datetime")
  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }

  public UserJson updatedAt(OffsetDateTime updatedAt) {
    this.updatedAt = updatedAt;
    return this;
  }

   /**
   * User last update datetime
   * @return updatedAt
  **/
  @ApiModelProperty(value = "User last update datetime")
  public OffsetDateTime getUpdatedAt() {
    return updatedAt;
  }

  public void setUpdatedAt(OffsetDateTime updatedAt) {
    this.updatedAt = updatedAt;
  }

  public UserJson id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(value = "")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UserJson userJson = (UserJson) o;
    return Objects.equals(this.name, userJson.name) &&
        Objects.equals(this.admin, userJson.admin) &&
        Objects.equals(this.enabled, userJson.enabled) &&
        Objects.equals(this.prospective, userJson.prospective) &&
        Objects.equals(this.publicKey, userJson.publicKey) &&
        Objects.equals(this.previousPublicKey, userJson.previousPublicKey) &&
        Objects.equals(this.lastLogin, userJson.lastLogin) &&
        Objects.equals(this.firstLogin, userJson.firstLogin) &&
        Objects.equals(this.lastLoginIp, userJson.lastLoginIp) &&
        Objects.equals(this.createdAt, userJson.createdAt) &&
        Objects.equals(this.updatedAt, userJson.updatedAt) &&
        Objects.equals(this.id, userJson.id);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, admin, enabled, prospective, publicKey, previousPublicKey, lastLogin, firstLogin, lastLoginIp, createdAt, updatedAt, id);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UserJson {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    admin: ").append(toIndentedString(admin)).append("\n");
    sb.append("    enabled: ").append(toIndentedString(enabled)).append("\n");
    sb.append("    prospective: ").append(toIndentedString(prospective)).append("\n");
    sb.append("    publicKey: ").append(toIndentedString(publicKey)).append("\n");
    sb.append("    previousPublicKey: ").append(toIndentedString(previousPublicKey)).append("\n");
    sb.append("    lastLogin: ").append(toIndentedString(lastLogin)).append("\n");
    sb.append("    firstLogin: ").append(toIndentedString(firstLogin)).append("\n");
    sb.append("    lastLoginIp: ").append(toIndentedString(lastLoginIp)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

