/*
 * CIRA SHG Windex API
 * CIRALabs SecureHomeGateway Windex API: between smartphone and router
 *
 * The version of the OpenAPI document: 1.0.0-current
 * Contact: securehomegateway@cira.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ca.cira.shg.windex.model;

import ca.cira.shg.windex.model.DeviceJson;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for Device
 */
public class DeviceTest {
    private final Device model = new Device();

    /**
     * Model tests for Device
     */
    @Test
    public void testDevice() {
        // TODO: test Device
    }

    /**
     * Test the property 'device'
     */
    @Test
    public void deviceTest() {
        // TODO: test device
    }

}
