/*
 * CIRA SHG Windex API
 * CIRALabs SecureHomeGateway Windex API: between smartphone and router
 *
 * The version of the OpenAPI document: 1.0.0-current
 * Contact: securehomegateway@cira.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ca.cira.shg.windex.model;

import ca.cira.shg.windex.model.DeviceBodyTrafficCounts;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.threeten.bp.OffsetDateTime;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for DeviceBody
 */
public class DeviceBodyTest {
    private final DeviceBody model = new DeviceBody();

    /**
     * Model tests for DeviceBody
     */
    @Test
    public void testDeviceBody() {
        // TODO: test DeviceBody
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'fqdn'
     */
    @Test
    public void fqdnTest() {
        // TODO: test fqdn
    }

    /**
     * Test the property 'eui64'
     */
    @Test
    public void eui64Test() {
        // TODO: test eui64
    }

    /**
     * Test the property 'createdAt'
     */
    @Test
    public void createdAtTest() {
        // TODO: test createdAt
    }

    /**
     * Test the property 'updatedAt'
     */
    @Test
    public void updatedAtTest() {
        // TODO: test updatedAt
    }

    /**
     * Test the property 'deviceTypeId'
     */
    @Test
    public void deviceTypeIdTest() {
        // TODO: test deviceTypeId
    }

    /**
     * Test the property 'manufacturerId'
     */
    @Test
    public void manufacturerIdTest() {
        // TODO: test manufacturerId
    }

    /**
     * Test the property 'idevId'
     */
    @Test
    public void idevIdTest() {
        // TODO: test idevId
    }

    /**
     * Test the property 'trafficCounts'
     */
    @Test
    public void trafficCountsTest() {
        // TODO: test trafficCounts
    }

    /**
     * Test the property 'mudUrl'
     */
    @Test
    public void mudUrlTest() {
        // TODO: test mudUrl
    }

    /**
     * Test the property 'profileId'
     */
    @Test
    public void profileIdTest() {
        // TODO: test profileId
    }

    /**
     * Test the property 'currentVlan'
     */
    @Test
    public void currentVlanTest() {
        // TODO: test currentVlan
    }

    /**
     * Test the property 'wanEnabled'
     */
    @Test
    public void wanEnabledTest() {
        // TODO: test wanEnabled
    }

    /**
     * Test the property 'lanEnabled'
     */
    @Test
    public void lanEnabledTest() {
        // TODO: test lanEnabled
    }

    /**
     * Test the property 'firewallRules'
     */
    @Test
    public void firewallRulesTest() {
        // TODO: test firewallRules
    }

    /**
     * Test the property 'firewallRuleNames'
     */
    @Test
    public void firewallRuleNamesTest() {
        // TODO: test firewallRuleNames
    }

    /**
     * Test the property 'deleted'
     */
    @Test
    public void deletedTest() {
        // TODO: test deleted
    }

    /**
     * Test the property 'quaranteed'
     */
    @Test
    public void quaranteedTest() {
        // TODO: test quaranteed
    }

    /**
     * Test the property 'deviceEnabled'
     */
    @Test
    public void deviceEnabledTest() {
        // TODO: test deviceEnabled
    }

    /**
     * Test the property 'deviceState'
     */
    @Test
    public void deviceStateTest() {
        // TODO: test deviceState
    }

    /**
     * Test the property 'failureDetails'
     */
    @Test
    public void failureDetailsTest() {
        // TODO: test failureDetails
    }

    /**
     * Test the property 'ipv4'
     */
    @Test
    public void ipv4Test() {
        // TODO: test ipv4
    }

    /**
     * Test the property 'ipv6'
     */
    @Test
    public void ipv6Test() {
        // TODO: test ipv6
    }

    /**
     * Test the property 'acpPrefix'
     */
    @Test
    public void acpPrefixTest() {
        // TODO: test acpPrefix
    }

    /**
     * Test the property 'idevidHash'
     */
    @Test
    public void idevidHashTest() {
        // TODO: test idevidHash
    }

    /**
     * Test the property 'ldevid'
     */
    @Test
    public void ldevidTest() {
        // TODO: test ldevid
    }

    /**
     * Test the property 'ldevidHash'
     */
    @Test
    public void ldevidHashTest() {
        // TODO: test ldevidHash
    }

    /**
     * Test the property 'wpaKey'
     */
    @Test
    public void wpaKeyTest() {
        // TODO: test wpaKey
    }

}
